services:
  koleksi-resep-client:
    build:
      context: .
      args:
        - API_URL:REACT_APP NAME=${REACT APP_NAME}
    container_name: koleksi-resep-client
    restart: unless-stopped
    ports:
      - "4001:80"
